# Generated by Django 2.2.7 on 2020-02-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('detail', models.TextField()),
            ],
        ),
    ]
